---
name: droid

on:
  issues:
    types:
    - opened
  issue_comment:
    types:
    - created
  pull_request:
    types:
    - opened

jobs:
  parse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      id: c-3po
      with:
        expect: |
          - pattern: ^/hello (?<value>.+)$
          - pattern: ^/chances (?<output>[^=]+)=(?<value>.*)$
          - command: intrusion
          - command: disappeared
            value: R2-D2
        description: 'true'

    - if: ${{ steps.c-3po.outputs.is-hello }}
      env:
        INPUTS_ARG1: "${{ steps.c-3po.outputs.has-hello }}"
        INPUTS_ARG2: ", it is you, it Is You!"
      uses: actions/github-script@v7
      with:
        script: |
          const args = [process.env.INPUTS_ARG1, process.env.INPUTS_ARG2]
          core.info(args.join(''))

    - if: ${{ steps.c-3po.outputs.is-chances && steps.c-3po.outputs.has-chances-survival }}
      env:
        INPUTS_ARG1: "R2 says the chances of survival are "
        INPUTS_ARG2: "${{ steps.c-3po.outputs.has-chances-survival }}"
        INPUTS_ARG3: "... to one"
      uses: actions/github-script@v7
      with:
        script: |
          const args = [process.env.INPUTS_ARG1, process.env.INPUTS_ARG2, process.env.INPUTS_ARG3]
          core.info(args.join(''))

    - if: ${{ steps.c-3po.outputs.is-chances && steps.c-3po.outputs.has-chances-win > 0 }}
      run: echo "We'll take the next chance, and the next."

    - if: ${{ steps.c-3po.outputs.is-intrusion }}
      run: echo "We're doomed"

    - if: ${{ steps.c-3po.outputs.is-disappeared }}
      run: echo "${{ steps.c-3po.outputs.has-disappeared }}, where are you?"
